services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/app/static
    depends_on:
      - db
    env_file:
      - ./.env.docker
    ports: 
      - "8000:8000"
    
  db:
    container_name: db
    image: postgres:17.0-alpine
    environment:
      POSTGRES_DB: rishat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/static
    depends_on:
      - web

volumes:
  pg_data:
  staticfiles:
