name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_AUTH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS }} << 'EOF'
            cd /root/rishat_assignment &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d --build
          EOF

